# Wire up travis
language: python
sudo: false

matrix:
    include:
        - python: 2.6
          env: TOXENV=py26
        - python: 2.7
          env: TOXENV=py27
        - python: 3.3
          env: TOXENV=py33
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
        - python: pypy
          env: TOXENV=pypy
        - python: pypy3
          env: TOXENV=pypy3
        - python: 3.5
          env: TOXENV=py2-cover,py3-cover,coverage

install:
  # https://github.com/travis-ci/travis-ci/issues/5027#issuecomment-170939193
  - |
      if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
        export PYENV_ROOT="$HOME/.pyenv"
        if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
          cd "$PYENV_ROOT" && git pull
        else
          rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
        fi
        export PYPY_VERSION="4.0.1"
        "$PYENV_ROOT/bin/pyenv" install "pypy-$PYPY_VERSION"
        virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
        source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
      fi
  - travis_retry pip install tox

script:
  - travis_retry tox

notifications:
  email:
    - pyramid-checkins@lists.repoze.org
