language: python
sudo: false
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - pypy
    - pypy3
install:
    - pip install .
script:
    - python setup.py -q test -q
notifications:
    email: pyramid-checkins@lists.repoze.org
